# this will trigger the build only on main branch and on PRs
if: branch = main

language: minimal

services:
  - docker

env:
  global:
    - IMAGE_NAME=transformer-engine
    - IMAGE_TAG=0.1.1
    - BUILD_IMAGE=true

install:
  - git clone -b t5_hf-lego https://$GIT_PAT@github.ibm.com/ai-foundation/foundation-model-stack
  - sh scripts/travis/build.sh
