# this will trigger the build only on main branch and on PRs
if: branch = main

language: minimal

services:
  - docker

env:
  global:
    - IMAGE_NAME=transformer-engine
    - IMAGE_TAG=0.2.3
    - BUILD_IMAGE=true

install:
  - git clone -b 0.0.0 https://$GIT_PAT@github.ibm.com/ai-models-architectures/megatron-models
  - sh scripts/travis/build.sh
