datasets:
  - class_name: MegatronDataset
    data_name: Megatron
    data_sampling_ratio: 1
    class_args:
      eval_steps: 2
      data_cache_path: /proj/checkpoints/mayank/cache
      data_path:
        - 0.35
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2016-26
        - 0.39
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2015-40
        - 0.41
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2016-18
        - 0.43
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2016-22
        - 0.47
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2016-36
        - 0.47
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2016-30
        - 0.47
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2016-07
        - 0.49
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2015-35
        - 0.49
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2015-48
        - 0.49
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2015-06
        - 0.49
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2015-11
        - 0.49
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2014-15
        - 0.52
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2016-40
        - 0.49
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2021-49
        - 0.50
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2020-34
        - 0.49
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2020-10
        - 0.52
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2015-22
        - 0.56
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2024-10
        - 0.52
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2019-47
        - 0.53
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2015-18
        - 0.51
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2014-42
        - 0.53
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2014-52
        - 0.57
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2021-25
        - 0.53
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2020-24
        - 0.55
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2019-13
        - 0.56
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2020-50
        - 0.54
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2018-34
        - 0.54
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2014-35
        - 0.55
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2019-26
        - 0.57
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2020-45
        - 0.55
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2019-30
        - 0.61
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2021-21
        - 0.57
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2019-18
        - 0.56
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2019-43
        - 0.56
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2014-41
        - 0.56
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2018-39
        - 0.58
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2014-23
        - 0.61
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2021-10
        - 0.58
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2019-04
        - 0.60
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2020-16
        - 0.61
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2019-09
        - 0.59
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2017-30
        - 0.59
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2017-22
        - 0.62
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2018-43
        - 0.62
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2018-26
        - 0.61
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2016-50
        - 0.61
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2017-47
        - 0.65
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2020-29
        - 0.62
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2022-05
        - 0.69
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2021-39
        - 0.63
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2016-44
        - 0.66
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2018-05
        - 0.66
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2018-51
        - 0.64
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2017-04
        - 0.65
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2018-09
        - 0.67
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2022-27
        - 0.65
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2017-26
        - 0.66
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2017-09
        - 0.71
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2022-40
        - 0.74
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2021-17
        - 0.73
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2023-14
        - 0.71
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2023-06
        - 0.67
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2017-34
        - 0.74
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2021-04
        - 0.74
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2020-40
        - 0.80
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2021-43
        - 0.79
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2021-31
        - 0.71
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2017-43
        - 0.77
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2022-21
        - 0.77
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2023-40
        - 0.78
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2017-13
        - 0.80
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2017-17
        - 0.51
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2022-33
        - 0.48
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2015-32
        - 0.53
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2013-20
        - 0.46
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2015-27
        - 0.44
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2014-49
        - 0.46
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2015-14
        - 0.52
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2019-39
        - 0.47
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2019-51
        - 0.60
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2019-35
        - 0.58
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2018-47
        - 0.64
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2020-05
        - 0.53
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2014-10
        - 0.52
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2018-22
        - 0.57
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2018-17
        - 0.59
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2017-51
        - 0.54
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2013-48
        - 0.57
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2019-22
        - 0.59
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2017-39
        - 0.63
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2018-13
        - 0.66
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2018-30
        - 0.74
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2022-49
        - 0.79
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2023-23
        - 0.87
        - /proj/datasets/training_data_starcoder_cleaned_0324/CC-MAIN-2023-50
        - 20
        - /proj/datasets/training_data_starcoder_cleaned_0324/starcoder-codepile-v02-L1-noGPL
        - 5
        - /proj/datasets/training_data_starcoder_cleaned_0324/dataset=webhose-1-en
        - 3
        - /proj/datasets/training_data_starcoder_cleaned_0324/dataset=uspto-1-en
        - 5
        - /proj/datasets/training_data_starcoder_cleaned_0324/peS2o+Arxiv+IEEE+DMMath+FinancialResearchPaper+Paperwithcode
        - 1
        - /proj/datasets/training_data_starcoder_cleaned_0324/dataset=wikimedia-1-en
        - 2
        - /proj/datasets/training_data_starcoder_cleaned_0324/Openwebmath_filtered+Algebraic-stack+Stackexchange
        - 2
        - /proj/datasets/training_data_starcoder_cleaned_0324/books_redpajama+doabooks
        - 2
        - /proj/datasets/training_data_starcoder_cleaned_0324/dataset=freelaw-1-en
        - 2
        - /proj/datasets/training_data_starcoder_cleaned_0324/dataset=pubmedcentral-1-en
        - 2
        - /proj/datasets/training_data_starcoder_cleaned_0324/EDGAR+Secfiling+FIDC+Earningcalltranscript
      split: 100,0,0
      sequence_length: 4096

tokenizer_args:
  tokenizer_name: bigcode/starcoder

model_args:
  model_class: AutoModelForCausalLM
  pretrained_config:
    activation_function: swiglu
    add_bias: false
    attention_softmax_in_fp32: true
    attn_pdrop: 0
    embd_pdrop: 0
    resid_pdrop: 0
    initializer_range: 0.1
    layer_norm_epsilon: 1e-05
    model_type: gpt_dolomite
    n_embd: 2304
    n_head: 36
    n_layer: 40
    n_positions: 4096
    normalization_function: rmsnorm
    position_embedding_type: rope
    rope_theta: 10000
    scale_attention_softmax_in_fp32: true
    attention_head_type: mha
    scale_attn_weights: true
    attention_multiplier: 0.015625
    vocab_size: 49152
    m_width: 9
    m_emb: 12
    m_residual: 0.22
    init_method: mup
    tie_word_embeddings: true
    bos_token_id: 0
    eos_token_id: 0
    pad_token_id: 0
  attention_implementation: flash_attention_2
  use_padding_free_transformer: true
  # reset_attention_mask: true
  # reset_position_ids: true

tuning_args:
  tuning_method: pretraining

save_args:
  save_path: /proj/checkpoints/mayank/3b-exp15-dolomite-fix
  save_interval: 5000

logging_args:
  log_interval: 10
  experiments_tracker_name: wandb
  wandb_args:
    project: granite-3b-experiments
    name: 3b-exp15-dolomite-fix

training_parameters:
  num_training_steps: 250000
  eval_interval: 2500000
  micro_batch_size: 2
  gradient_accumulation_steps: 2
  eval_during_training: false

optimizer_args:
  params_group_method: mup
  class_name: TorchAdamW
  class_args:
    lr: 0.02
    weight_decay: 0.1
    betas:
      - 0.9
      - 0.95
    eps: 1e-10

lr_scheduler_args:
  lr_decay_style: power
  num_warmup_steps: 2500
  num_constant_steps: 0
  num_decay_steps: 247500
  extra_lr_scheduler_args:
    # 4 * global_batch_size
    a: 4096
    # constant
    b: -0.51
    # global_batch_size in number of tokens
    c: 4194304

mixed_precision_args:
  dtype: bf16

distributed_args:
  distributed_backend: torch
  stage: 3
  zero_hpz_partition_size: 8
  timeout_minutes: 300
