load_args:
  load_path: checkpoints
  iteration: 5000

mixed_precision_args:
  # if you want to save the exported model in fp32, if not specified,
  # its taken from the training config in the saved checkpoint
  dtype: fp32

# where to save the HF safetensors checkpoint
export_path: exported_huggingface_model
