datasets:
  - class_name: JSONLinesDataset
    class_args:
      num_examples: 100
    data_name: code_instruct_mix_super
    data_sampling_ratio: 1
    max_input_tokens: 4096
    max_output_tokens: 4096

model_args:
  model_name: ibm-granite/granite-3b-code-base
  model_class: AutoModelForCausalLM
  attention_implementation: flash_attention_2

tuning_args:
  tuning_method: full_finetuning

save_args:
  save_path: checkpoints
  save_interval: 10000

training_parameters:
  num_training_steps: 28467
  eval_during_training: false
  micro_batch_size: 4
  gradient_accumulation_steps: 1

optimizer_args:
  class_name: TorchAdamW
  class_args:
    lr: 1e-5
    weight_decay: 0.1
    betas:
      - 0.9
      - 0.95
    eps: 1e-10

lr_scheduler_args:
  lr_decay_style: cosine

mixed_precision_args:
  dtype: bf16
