name: Style Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style-check:
    name: Check Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort black

      - name: Check Python Files with isort and black
        run: |
          isort --check-only .
          black --check .

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Check C/C++ Files with clang-format
        run: |
          find . -name '*.cpp' -o -name '*.c' -o -name '*.h' | xargs clang-format -style=file -output-replacements-xml | grep "<replacement " && exit 1 || true
